/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MusicList` | `/MusicList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen` | `/SearchScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/UserScreen` | `/UserScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/AlbumScreen` | `/SearchScreen/AlbumScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/MusicPlayerScreen` | `/SearchScreen/MusicPlayerScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/SearchScreen` | `/SearchScreen/SearchScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MusicList` | `/MusicList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SearchScreen` | `/SearchScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/UserScreen` | `/UserScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/AlbumScreen` | `/SearchScreen/AlbumScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/MusicPlayerScreen` | `/SearchScreen/MusicPlayerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/SearchScreen` | `/SearchScreen/SearchScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LibraryScreen${`?${string}` | `#${string}` | ''}` | `/LibraryScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MusicList${`?${string}` | `#${string}` | ''}` | `/MusicList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/RegisterScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SearchScreen${`?${string}` | `#${string}` | ''}` | `/SearchScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/UserScreen${`?${string}` | `#${string}` | ''}` | `/UserScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SearchScreen/AlbumScreen${`?${string}` | `#${string}` | ''}` | `/SearchScreen/AlbumScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SearchScreen/MusicPlayerScreen${`?${string}` | `#${string}` | ''}` | `/SearchScreen/MusicPlayerScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SearchScreen/SearchScreen${`?${string}` | `#${string}` | ''}` | `/SearchScreen/SearchScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MusicList` | `/MusicList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen` | `/SearchScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/UserScreen` | `/UserScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/AlbumScreen` | `/SearchScreen/AlbumScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/MusicPlayerScreen` | `/SearchScreen/MusicPlayerScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SearchScreen/SearchScreen` | `/SearchScreen/SearchScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
